USE [master]
GO

/****** Object:  Database [FormLogin]    Script Date: 3/12/2019 10:11:59 PM ******/
CREATE DATABASE [FormLogin] ON  PRIMARY 
( NAME = N'FormLogin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\FormLogin.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FormLogin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\FormLogin_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FormLogin] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FormLogin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FormLogin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FormLogin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FormLogin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FormLogin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FormLogin] SET ARITHABORT OFF 
GO

ALTER DATABASE [FormLogin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FormLogin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FormLogin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FormLogin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FormLogin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FormLogin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FormLogin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FormLogin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FormLogin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FormLogin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FormLogin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FormLogin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FormLogin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FormLogin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FormLogin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FormLogin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FormLogin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FormLogin] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FormLogin] SET  MULTI_USER 
GO

ALTER DATABASE [FormLogin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FormLogin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FormLogin] SET  READ_WRITE 
GO

